config/routes.rb
Furcons::Application.routes.draw do
	resource :session
	get "signin" => "sessions#new"
	resources :users
	get "signup" => "users#new"

	get 'furcons/:scope' => "furcons#index", constraints: { scope: /everything|upcoming_prereg|upcoming|past|recent/ }, as: :filtered_furcons
	
	root "furcons#index"
	resources :furcons do
		resources :memberships
	end
end

app/models/furcon.rb
class Furcon < ActiveRecord::Base
	has_many :memberships, dependent: :destroy

	before_validation :generate_slug

	validates :name, presence: true, uniqueness: true
	validates :slug, uniqueness: true
	validates :website, :location, :starts_on, :ends_on, :prereg_by, presence: true
	validates :image_file_name, allow_blank: true, format: {
		with: /\w+.(gif|jpg|png)\z/i,
		message: "must reference a GIF, JPG, or PNG image"
	}

	scope :everything, -> { order(starts_on: :asc) }
	scope :upcoming, -> { where("starts_on >= ?", Time.now).order(starts_on: :asc) }
	scope :upcoming_prereg, -> { upcoming.where("prereg_by >= ?", Time.now).order(prereg_by: :asc) }
	scope :past, -> { where("starts_on < ?", Time.now).order(starts_on: :desc) }
	scope :recent, ->(r=3) { past.limit(r) }
	
	def charity?
		charities.blank?
	end

	def to_param
		slug
	end

	def generate_slug
		self.slug ||= name.parameterize if name
	end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
	belongs_to :furcon

	validates :name, :prereg_fee, :reg_fee, presence: true
	validate :swag, allow_blank: true

	def prna?
		prereg_fee <= 0
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	before_validation :generate_slug

	has_secure_password
	
	validates :name, presence: true, uniqueness: true
	validates :slug, uniqueness: true
	validates :email, presence: true, format: /\A\S+@\S+\z/, uniqueness: { case_sensitive: false }
	validates :password, length: { minimum: 5, allow_blank: true }
	validates :username, presence: true, format: /\A[A-Z0-9]+\z/i, uniqueness: { case_sensitive: false }

=begin
	ADMIN = ['yes', 'no']

	validates :admin, inclusion: { 
		in: ADMIN
	}

			<li>
				<%= f.label :admin, "Are you an Admin?" %>
				<% User::ADMIN.each do |x| %>
					<span>
						<%= f.radio_button :admin, x %> <%= x %>
					</span>
				<% end %>
			</li>
=end

	scope :by_name, -> { order(:name) }
	scope :not_admins, -> { by_name.where(admin: false) }
	
	def gravatar_id
		Digest::MD5::hexdigest(email.downcase)
	end

	def self.authenticate(email_or_username, password)
		user = User.find_by(email: email_or_username) || User.find_by(username: email_or_username)
		user && user.authenticate(password)
	end

	def to_param
		slug
	end

	def generate_slug
		self.slug ||= name.parameterize if name
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception

private
	def set_session_url
		session[:intended_url] = request.url
	end

	def require_signin
		unless current_user
			set_session_url
			redirect_to new_session_url, alert: "Please sign in first!"
		end
	end

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	helper_method :current_user

	def current_user?(user)
		current_user == user
	end

	helper_method :current_user?

	def require_admin
		unless current_user_admin?
			set_session_url
			redirect_to root_url, alert: "Unauthorized access!"
		end
	end

	def current_user_admin?
		current_user && current_user.admin?
	end

	helper_method :current_user_admin?

end

app/controllers/furcons_controller.rb
class FurconsController < ApplicationController
	before_action :require_signin, except: [:index, :show]
	before_action :require_admin, except: [:index, :show]
	before_action :set_furcon, only: [:show, :edit, :update, :destroy]

	def index
		@furcons = Furcon.send(furcons_scope)
	end

	def show
	end

	def edit
	end

	def update
		if @furcon.update(furcon_params)
			redirect_to @furcon, notice: "Furcon successfully updated!"
		else
			render :edit
		end
	end

	def new
		@furcon = Furcon.new
	end

	def create
		@furcon = Furcon.new(furcon_params)
		if @furcon.save
			redirect_to @furcon, notice: "Furcon successfully created!"
		else
			render :new
		end
	end

	def destroy
		@furcon.destroy
		redirect_to furcons_url, alert: "Furcon successfully deleted!"
	end

private
	def furcon_params
		furcon_params = params.require(:furcon).permit(:name, :website, :location, :theme, :starts_on, :ends_on, :prereg_by, :charities, :guest_of_honor, :image_file_name, :slug)
	end

	def furcons_scope
		if params[:scope].in? %w(past upcoming_prereg everything upcoming recent)
			params[:scope]
		else
			:upcoming
		end
	end

	def set_furcon
		@furcon = Furcon.find_by!(slug: params[:id])
	end

end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
	before_action :require_signin, except: [:index, :show]
	before_action :require_admin, except: [:index, :show]
	before_action :set_furcon

	def index
		@memberships = @furcon.memberships
	end
	
	def new
		@membership = @furcon.memberships.new
	end

	def create
		@membership = @furcon.memberships.new(membership_params)
		if @membership.save
			redirect_to furcon_memberships_path(@furcon), notice: "Membership added!"
		else
			render :new
		end
	end

	def edit
		@membership = Membership.find(params[:id])
	end

	def update
		@membership = Membership.find(params[:id])
		if @membership.update(membership_params)
			redirect_to furcon_memberships_path(@furcon), notice: "Membership successfully updated!"
		else
			render :edit
		end
	end

	def destroy
		@membership = Membership.find(params[:id])
		@membership.destroy
		redirect_to furcon_memberships_path(@furcon), alert: "Membership successfully deleted!"
	end

private
	def membership_params
		params.require(:membership).permit(:name, :swag, :prereg_fee, :reg_fee)
	end

	def set_furcon
		@furcon = Furcon.find_by!(slug: params[:furcon_id])
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end

	def create
		if user = User.authenticate(params[:email_or_username], params[:password])
			session[:user_id] = user.id
			flash[:notice] = "Welcome back, #{user.name}!"
			redirect_to(session[:intended_url] || user)
			session[:intended_url] = nil

		else
			flash.now[:alert] = "Invalid login/password combination!"
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url, notice: "You're now signed out!"
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :require_signin, except: [:new, :create]
	before_action :require_correct_user, only: [:edit, :update, :destroy]
	before_action :set_user, only: [:show, :edit, :update, :destroy]

	def index
		if current_user_admin?
			@users = User.by_name
		else
			@users = User.not_admins
		end
	end

	def show
	end
	
	def new
		@user = User.new
	end
	
	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to @user, notice: "Thanks for signing up!"
		else
			render :new
		end 
	end

	def edit
	end

	def update
		if @user.update(user_params)
			redirect_to @user, notice: "Account successfully updated!"
		else
			render :edit
		end
	end

	def destroy
		@user.destroy
		session[:user_id] = nil
		redirect_to root_url, alert: "Account successfully deleted!"
	end

private
	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation, :username, :slug, :admin)
	end

	def require_correct_user
		@user = User.find_by!(slug: params[:id])
		redirect_to root_url unless current_user?(@user)
	end

	def set_user
		@user = User.find_by!(slug: params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def page_title
		if content_for?(:title)
			content_tag(:title, "Furcons - #{content_for(:title)}")
		else
			content_tag(:title, "Furcons")
		end
	end

	def nav_link_to(text, url)
		classes = ['button']
		classes << 'active' if current_page?(url)
		link_to(text, url, class: classes.join(' '))
	end
end

app/helpers/furcons_helper.rb
module FurconsHelper
	def format_charity(furcon)
		if furcon.charity?
			content_tag(:strong, 'No Charity Yet')
		else
			furcon.charities
		end
	end
	def image_for(furcon)
		if furcon.image_file_name.blank?
			image_tag('placeholder.gif')
		else
			image_tag(furcon.image_file_name)
		end
	end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
	def format_prereg_fee(membership)
		if membership.prna?
			content_tag(:strong, '~*~')
		else
			number_to_currency(membership.prereg_fee)
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def profile_image_for(user)
		url = "https://secure.gravatar.com/avatar/#{user.gravatar_id}"
		image_tag(url, alt: user.name)
	end
end

app/views/furcons/_form.html.erb
<%= form_for(@furcon) do |f| %>
	<%= render "shared/errors", object: @furcon %>
	<fieldset>
		<ol>
			<li class="required">
				<%= f.label :name %>
				<%= f.text_field :name, size: 50, autofocus: true %>
			</li>
			<li class="required">
				<%= f.label :website %>
				<%= f.text_field :website, size: 50 %>
			</li>
			<li class="required">
				<%= f.label :location %>
				<%= f.text_area :location, cols: 50, rows: 2 %>
			</li>
			<li>
				<%= f.label :theme %>
				<%= f.text_field :theme, size: 50 %>
			</li>
			<li>
				<%= f.label :starts_on %>
				<%= f.date_select :starts_on %>
			</li>
			<li>
				<%= f.label :ends_on %>
				<%= f.date_select :ends_on %>
			</li>
			<li>
				<%= f.label :charities %>
				<%= f.text_field :charities, size: 50 %>
			</li>
			<li>
				<%= f.label :guest_of_honor %>
				<%= f.text_field :guest_of_honor, size: 50 %>
			</li>
			<li>
				<%= f.label :prereg_by %>
				<%= f.date_select :prereg_by %>
			</li>
			<li>
				<%= f.label :image_file_name %>
				<%= f.text_field :image_file_name, size: 30, placeholder: "GIF, JPG, or PNG file name" %>
			</li>
			<% unless @furcon.new_record? %>
				<li>
					<%= f.label :slug %>
					<%= f.text_field :slug, size: 30 %>
				</li>
			<% end %>
		</ol>
		<p>
			<%= f.submit %>
			<%= link_to "Cancel", furcons_path, class: 'button' %>
		</p>
	</fieldset>
<% end %>

app/views/furcons/edit.html.erb
<h1>Editing <%= @furcon.name %></h1>

<%= render 'form' %>

app/views/furcons/index.html.erb
<ul id="furcons">
	<% @furcons.each do |furcon| %>
		<li>
			<article class="furcon">
				<header>
					<%= image_for(furcon) %>
					<h2><%= link_to furcon.name, furcon %></h2>
					<h3><a href="<%= furcon.website %>" target="_blank"><%= furcon.website %></a></h3>
				</header>
				<table>
					<tr>
						<th>Location</th>
						<td><%= furcon.location %></td>
					</tr>
					<tr>
						<th>Theme</th>
						<td><%= furcon.theme %></td>
					</tr>
					<tr>
						<th>Dates</th>
						<td><%= furcon.starts_on %> to <%= furcon.ends_on %></td>
					</tr>
				</table>
				<footer>
				</footer>
			</article>
		</li>
	<% end %>
</ul>

app/views/furcons/new.html.erb
<header id="content-header">
	<h1>Create a New Furcon</h1>
</header>

<%= render 'form' %>

app/views/furcons/show.html.erb
<% content_for(:title, @furcon.name) %>

<article id="furcon" class="furcon">
	<header>
		<%= image_for(@furcon) %>
		<h1><%= @furcon.name %></h1>
	</header>
	<h2>Website:</h2>
	<p>
		<a href="<%= @furcon.website %>" target="_blank"><%= @furcon.website %></a>
	</p>
	<h3>Location:</h3>
	<p>
		<%= @furcon.location %>
	</p>
	<h3>Theme:</h3>
	<p>
		<%= @furcon.theme %>
	</p>
	<h3>Dates:</h3>
	<p>
		<%= @furcon.starts_on %> to <%= @furcon.ends_on %>
 	</p>
	<h3>Charities:</h3>
	<p>
		<%= format_charity(@furcon) %>
	</p>
	<h3>Guest of Honor:</h3>
	<p>
		<%= @furcon.guest_of_honor %>
	</p>
	<h3>PreRegistration Ends:</h3>
	<p>
		<%= @furcon.prereg_by %>
	</p>
	<p>
		<%= link_to pluralize(@furcon.memberships.size, "membership"), furcon_memberships_path(@furcon) %>
	</p>
	<footer>
		<nav>
		<% if current_user_admin? %>
			<p>
				<%= link_to "Add a Membership", new_furcon_membership_path(@furcon), class: 'button ok membership' %>
			</p>		
			<%= link_to 'Edit', edit_furcon_path(@furcon), class: 'button' %>
			<%= link_to 'Delete', @furcon, class: 'button', method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
		</nav>
	</footer>
</article>

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
	<%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2013
    <%= link_to 'The Pragmatic Studio', 'http://pragmaticstudio.com' %>
  </p>
  <p>
    For educational purposes only.
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
	<div id="masthead">
		<h1><%= link_to 'Furcons', root_path %></h1>
		<nav>
			<p>
				<% if current_user %>
					<%= link_to current_user.name, current_user %>
					<%= link_to "Account Settings", edit_user_path(current_user), class: 'button'  %>
					<%= link_to "Sign Out", session_path, method: :delete, class: 'button' %>
				<% else %>
					<%= link_to 'Sign Up', signup_path, class: 'button' %>
					<%= link_to 'Sign In', signin_path, class: 'button' %>
				<% end %>
			</p>
		</nav>
	</div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
	<nav>
		<ul>
			<li class="furcons">
				<%= nav_link_to 'All Furcons', filtered_furcons_path(:everything) %>
			</li>
			<li class="furcons">
				<%= nav_link_to 'Can still PreReg!', filtered_furcons_path(:upcoming_prereg) %>
			</li>
			<li class="furcons">
				<%= nav_link_to 'Upcoming', furcons_path %>
			</li>
			<li class="furcons">
				<%= nav_link_to 'Past', filtered_furcons_path(:past) %>
			</li>
			<li class="furcons">
				<%= nav_link_to 'Recent', filtered_furcons_path(:recent) %>
			</li>
		<% if current_user_admin? %>
			<li class="create-furcon">
				<%= nav_link_to 'Add New Furcon', new_furcon_path %>
			</li>
			<li class="edit-users">
				<%= nav_link_to 'Edit Users', users_path %>
			</li>
		<% end %>
		</ul>
	</nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<%= page_title %>
	<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
	<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	<%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<div id="wrapper">

<%= render "layouts/flashes" %>

	<div id="container">
		<section id="sidebar">
			<%= render "layouts/sidebar" %>
		</section>
		<section id="content">
			<%= yield %>
		</section>
	</div>

</div>

<%= render "layouts/footer" %>

</body>
</html>

app/views/memberships/_form.html.erb
<%= form_for([@furcon, @membership]) do |f| %>
	<%= render "shared/errors", object: @membership %>
	<fieldset>
		<ol>
			<li class="required">
				<%= f.label :name %>
				<%= f.text_field :name, size: 40, autofocus: true, placeholder: "Nifty type you are..." %>
			</li>
			<li class="required">
				<%= f.label :prereg_fee %>
				<%= f.number_field :prereg_fee %>
			</li>
			<li class="required">
				<%= f.label :reg_fee %>
				<%= f.number_field :reg_fee %>
			</li>
			<li class="required">
				<%= f.label :swag %>
				<%= f.text_area :swag, cols: 80, rows: 8, placeholder: "What you get for your Niftyness..." %>
			</li>
		</ol>
		<p>
			<%= f.submit %> 
			<%= link_to "Cancel", furcon_memberships_path(@furcon), class: 'button' %>
		</p>
	</fieldset>
<% end %>

app/views/memberships/edit.html.erb
<header id="content-header">
	<h1>
		Edit Membership for<br/>
		<%= link_to(@furcon.name, @furcon) %>
	</h1>
</header>

<%= render 'form' %>

app/views/memberships/index.html.erb
<header id="content-header">
	<h1>
		Memberships for<br/>
		<%= link_to(@furcon.name, @furcon) %>
	</h1>
</header>

<ol id="memberships">
	<% @memberships.each do |membership| %>
		<li>
			<span class="user"><%= membership.name %></span>
			<% if current_user_admin? %>
				<%= link_to 'Edit Me', edit_furcon_membership_path(@furcon, membership), class: 'button' %>
				<%= link_to 'Delete Me', furcon_membership_path(@furcon, membership), class: 'button', method: :delete, data: { confirm: "Are you sure you want to delete #{membership.name.upcase}?" } %>
			<% end %>
			<p>
				<span>
					<%= format_prereg_fee(membership) %><br/>
					<%= number_to_currency(membership.reg_fee) %> after PreRegistration Date
					<br/>
				</span>
				<%= membership.swag %>
			</p>
		</li>
	<% end %>
</ol>

app/views/memberships/new.html.erb
<header id="content-header">
	<h1>
		New Membership for<br/>
		<%= link_to(@furcon.name, @furcon) %>
	</h1>
</header>

<%= render 'form' %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
	<header>
		<h2>
			Oops! The <%= object.class.name.humanize.downcase %> could not be saved. 
		</h2>
		<h3>
			Please correct the following <%= pluralize(object.errors.count, "error") %>:
		</h3>
	</header>
	<ul>
		<% object.errors.full_messages.each do |message| %>
			<li><%= message %></li>
		<% end %>
	</ul>
</section>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
	<%= render "shared/errors", object: @user %>
	<fieldset>
		<ol>
			<li class="required">
				<%= f.label :name %>
				<%= f.text_field :name, size: 40, autofocus: true %>
			</li>
			<li class="required">
				<%= f.label :username %>
				<%= f.text_field :username, size: 40, placeholder: "Alphanumeric characters only!" %>
			</li>
			<li class="required">
				<%= f.label :email %>
				<%= f.email_field :email, size: 40 %>
			</li>
			<li class="required">
				<%= f.label :password %>
				<%= f.password_field :password, size: 40 %>
			</li>
			<li class="required">
				<%= f.label :password_confirmation, "Confirm Password" %>
				<%= f.password_field :password_confirmation, size: 40 %>
			</li>

			<% unless @user.new_record? %>
				<li>
					<%= f.label :slug %>
					<%= f.text_field :slug, size: 30 %>
				</li>
			<% end %>
		</ol>
		<p>
			<% if @user.new_record? %>
				<%= f.submit "Create Account" %>
			<% else %>
				<%= f.submit "Update Account" %>
			<% end %>
		</p>
	</fieldset>
<% end %>

app/views/users/edit.html.erb
<header id="content-header">
	<h1>Edit Account</h1>
</header>

<%= render 'form' %>

app/views/users/index.html.erb
<header id="content-header">
	<h1><%= pluralize(@users.size, 'User') %></h1>
</header>

<ul id="users">
	<% @users.each do |user| %>
		<li>
			<%= link_to user.name, user %>
			
		</li>
	<% end %>
</ul>

app/views/users/new.html.erb
<header id="content-header">
	<h1>Sign Up</h1>
</header>

<%= render 'form' %>

app/views/users/show.html.erb
<% content_for(:title, @user.name) %>

<article id="user">
	<header>
		<%= profile_image_for(@user) %>
		<h1><%= @user.name %></h1>
		<h2><%= mail_to(@user.email) %></h2>
		<h2><%= @user.username %></h2>
		<h3>Member Since</h3>
		<p>
			<%= @user.created_at.strftime("%B %Y") %>
		</p>
	</header>
</article>

<footer>
	<nav>
	<% if current_user?(@user) %>
		<%= link_to 'Edit Account', edit_user_path(@user), class: 'button' %>
		<%= link_to 'Delete Account', @user, method: :delete, data: { confirm: 'Are you sure you want to permanently delete your account?' }, class: 'button' %>
	<% end %>
	</nav>
</footer>